name: crud_operations
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.5 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  json_annotation: ^4.8.0
  flutter: 
    sdk: flutter
  dio: ^5.4.0
  logger: ^2.0.2+1
  dartz: ^0.10.1
  get_it: ^7.6.7
  flutter_spinkit: ^5.2.0
  drift_sqflite: ^2.0.1
  drift: ^2.15.0
  build_runner: ^2.4.8
  sqflite: ^2.3.2
  sqlite3_flutter_libs: ^0.5.19+1
  path_provider: ^2.1.2
  path: ^1.8.3

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
  json_serializable: ^6.6.0  
  freezed: ^2.4.6
  drift_dev: ^2.15.0
  

flutter: 
  uses-material-design: true

  assets:
    - asset/images/